### ISSUE TITLE
Floor plans are not updating when exhibitors are added

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/PowerOfAge-Website#8]
I imagine this is because the page name of the exhibitor content collection was changed from 2017-exhibitors.html to 2018-exhibitors.html, so the floor plan is now looking for the data in the wrong place.

http://www.powerofageexpo.com/floor-plan/north-hall.html
http://www.powerofageexpo.com/floor-plan/south-hall.html

http://www.powerofageexpo.com/exhibitors/2018-exhibitors.html

**Comment by martypowell** [comment]
@danfox01 this would probably be a good opportunity for me to take the reigns from @mxsnyder

**Comment by mxsnyder** [comment]
Code change needed in senior-expo-booths.min.js, which is pointed at the 2017 list.

**Comment by mxsnyder** [comment]
(or make this a config setting)

**Comment by danfox01** [comment]
@martypowell, I believe the fix for this was this merged and put into production here: https://github.com/baltimorecounty/PowerOfAge-Website/pull/9. Can please confirm that sounds right to you?

There was never a release created for this, so once I hear from you, I'll add one just so things are documented.

**Comment by martypowell** [comment]
@danfox01 looks right to me.

**Comment by danfox01** [comment]
@martypowell thanks
